spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
    exemple-kafka: topic_exemple_kafka

server:
  port: 8081
  servlet:
    context-path: /producer